client:
  base-url: http://localhost:5173

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_token_login
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: ${APPLE_CLIENT_ID}
            team-id: ${APPLE_TEAM_ID}
            key-id: ${APPLE_KEY_ID}
            key-path: ${APPLE_KEY_PATH}
            client-authentication-method: client_secret_post
            redirect-uri: ${client.base-url}/login/callback/apple
            authorization-grant-type: authorization_code
            scope:
              - openid
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${client.base-url}/login/callback/kakao
            authorization-grant-type: authorization_code
            scope:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${client.base-url}/login/callback/naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
          dev:
            provider: kakao
            client-id: ${DEV_CLIENT_ID}
            client-secret: ${DEV_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${client.base-url}/login/callback/dev
            authorization-grant-type: authorization_code
            scope:
        provider:
          apple:
            issuer-uri: https://appleid.apple.com
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id  # oidc일 경우 sub
          naver:
            issuer-uri: https://nid.naver.com
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response/id
  jackson:
    property-naming-strategy: SNAKE_CASE

authorization:
  token:
    issuer: http://localhost:8080
    audiences:
      - http://localhost:8080
    access-token-time-to-live: 30m
    refresh-token-time-to-live: 90d
  authorization-base-uri: /oauth2/authorization
  redirection-base-uri: /login/oauth2/code
  token-uri: /oauth2/token
  redirect-uri-parameter-allowed-registrations:
    - dev
