client:
  base-url: http://localhost:5173

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_token_login
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${client.base-url}/login/callback
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id

authorization:
  issuer: http://localhost:8080
  audience: http://localhost:8080
  access-token-time-to-live: 1800
  refresh-token-time-to-live: 7776000
